
services:
  minio:
    image: minio/minio:latest
    container_name: br_minio
    ports:
      - "9000:9000" # S3 API Port
      - "9001:9001" # Web Console Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Password@123
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
