export const queryKeys = {
  home: ["home-snapshot"],
  products: (search) => ["products", search],
  product: (productId, userId) => ["product", productId, userId],
  cart: (userId, couponCode) => ["cart", userId, couponCode],
  favorites: (userId) => ["favorites", userId],
  orders: (userId) => ["orders", userId],
  orderTracking: (orderId, userId) => ["tracking", orderId, userId],
  refunds: (userId) => ["refund-requests", userId],
  profile: (userId) => ["profile", userId],
  contentPage: (page) => ["content-page", page],
  adminDashboard: ["admin", "dashboard"],
  adminProducts: (search = "", page = 1) => ["admin", "products", search, page],
  adminCategories: ["admin", "categories"],
  adminFeaturedProducts: ["admin", "products", "featured"],
  adminUsers: ["admin", "users"],
  adminUserDetails: (userId) => ["admin", "users", userId],
  adminOrders: (filter = "all") => ["admin", "orders", filter],
  adminOrderDetails: (orderId) => ["admin", "orders", orderId],
  adminRefunds: (filter = "all") => ["admin", "refunds", filter],
  adminHomeContent: ["admin", "content", "home"],
  adminContentPage: (page) => ["admin", "content", page],
  adminBanners: ["admin", "content", "banners"],
  adminBlogs: ["admin", "blogs"],
  adminAnalytics: ["admin", "analytics"],
  adminFinance: ["admin", "finance"],
  adminSettings: ["admin", "settings"],
};
