export const routes = {
  root: "/",
  appHome: "/",
  appProducts: "/products",
  appProductDetails: (slug = ":slug") => `/products/${slug}`,
  appAbout: "/about",
  appContact: "/contact",
  appBlogs: "/blogs",
  appBlogDetails: (id = ":id") => `/blogs/${id}`,
  appCart: "/cart",
  appFavorites: "/favorites",
  appOrders: "/orders",
  appOrderTracking: (orderId = ":orderId") => `/orders/${orderId}/tracking`,
  appReturns: "/returns",
  appProfile: "/profile",
  appChangePassword: "/change-password",
  adminDashboard: "/admin/dashboard",
  adminProductsList: "/admin/products/list",
  adminProductCreate: "/admin/products/create",
  adminProductEdit: (productId = ":productId") => `/admin/products/${productId}/edit`,
  adminProductDetails: (productId = ":productId") => `/admin/products/${productId}`,
  adminCategories: "/admin/products/categories",
  adminFeaturedProducts: "/admin/products/featured",
  adminBulkUpload: "/admin/products/bulk-upload",
  adminUsersList: "/admin/users/list",
  adminUserDetails: (userId = ":userId") => `/admin/users/details/${userId}`,
  adminOrdersAll: "/admin/orders/all",
  adminOrdersPending: "/admin/orders/pending",
  adminOrderTracking: "/admin/orders/tracking",
  adminRefundRequests: "/admin/refunds/requests",
  adminRefundStatus: "/admin/refunds/status",
  adminContentHome: "/admin/content/home",
  adminContentAbout: "/admin/content/about",
  adminContentContact: "/admin/content/contact",
  adminContentBanners: "/admin/content/banners",
  adminContentBlogs: "/admin/content/blogs",
  adminAnalytics: "/admin/analytics",
  adminFinance: "/admin/analytics/finance",
  adminCouponsList: "/admin/coupons/list",
  adminCouponsAssign: "/admin/coupons/assign",
  adminSettings: "/admin/settings",
  adminProfile: "/admin/profile",
  adminChangePassword: "/admin/change-password",
};

export const userNavigation = [
  { labelKey: "nav.home", to: routes.appHome },
  { labelKey: "nav.products", to: routes.appProducts },
  { labelKey: "nav.blogs", to: routes.appBlogs },
  { labelKey: "nav.about", to: routes.appAbout },
  { labelKey: "nav.contact", to: routes.appContact },
];

export const userRouteRedirects = [
  { from: "/app", to: "/" },
  { from: "/app/products", to: "/products" },
  { from: "/app/products/:productId", to: "/products/:productId" },
  { from: "/app/about", to: "/about" },
  { from: "/app/contact", to: "/contact" },
  { from: "/app/cart", to: "/cart" },
  { from: "/app/favorites", to: "/favorites" },
  { from: "/app/orders", to: "/orders" },
  { from: "/app/orders/:orderId/tracking", to: "/orders/:orderId/tracking" },
  { from: "/app/returns", to: "/returns" },
  { from: "/app/profile", to: "/profile" },
];

export const adminRouteRedirects = [
  { from: "products", to: routes.adminProductsList },
  { from: "categories", to: routes.adminCategories },
  { from: "users", to: routes.adminUsersList },
  { from: "users/details", to: routes.adminUsersList },
  { from: "orders", to: routes.adminOrdersAll },
  { from: "refunds", to: routes.adminRefundRequests },
  { from: "content", to: routes.adminContentHome },
  { from: "finance", to: routes.adminFinance },
];
